FT_DPCM_PTR=$c000
;this file for FamiTone2 library generated by text2data tool
	.export _musica_music_data
_musica_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $30 ;instrument $05
	.word @env1,@env2,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$c7,$c5,$c3,$ce,$c0,$00,$05
@env2:
	.byte $c0,$c0,$c3,$c3,$c8,$c8,$00,$05


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $80,$3a,$3a,$3a,$3a,$3a,$3a,$3c,$3c,$3c,$3c,$3c,$3c,$3a,$3a,$3a
	.byte $3a,$3a,$3a,$3a,$3a,$36,$36,$36,$36,$32,$32,$36,$32,$32,$36,$32
	.byte $32,$48,$bd
@ref1:
	.byte $3a,$3a,$3a,$3a,$3a,$3a,$3c,$3c,$3c,$3c,$3c,$3c,$3a,$3a,$3a,$3a
	.byte $3a,$3a,$3a,$3a,$36,$36,$36,$36,$32,$32,$36,$32,$32,$36,$32,$32
	.byte $48,$bd
	.byte $ff,$22
	.word @ref1
	.byte $ff,$22
	.word @ref1
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref4:
	.byte $f9,$85
@ref5:
	.byte $f9,$85
@ref6:
	.byte $f9,$85
@ref7:
	.byte $f9,$85
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref8:
	.byte $c3,$80,$48,$3a,$3a,$3a,$3a,$3a,$36,$32,$36,$36,$32,$36,$32,$3a
	.byte $36,$32,$3a,$36,$3a,$3a,$3a,$36,$36,$36,$36,$89
@ref9:
	.byte $c3,$48,$3a,$3a,$3a,$3a,$3a,$36,$32,$36,$36,$32,$36,$32,$3a,$36
	.byte $32,$3a,$36,$3a,$3a,$3a,$36,$36,$36,$36,$89
	.byte $ff,$1b
	.word @ref9
	.byte $ff,$1b
	.word @ref9
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref12:
	.byte $f5,$80,$0c,$0a,$0c,$00,$81
@ref13:
	.byte $f5,$0c,$0a,$0c,$00,$81
	.byte $ff,$06
	.word @ref13
	.byte $ff,$06
	.word @ref13
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref16:
	.byte $f9,$85
@ref17:
	.byte $f9,$85
@ref18:
	.byte $f9,$85
@ref19:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop
